#!/usr/bin/env bash

# Startup script to run mnb outside of container (requires python3)

set -o errexit

if [ ! -d ./mnb-main/venv ]
then
    mkdir ./mnb-main/venv
    virtualenv ./mnb-main/venv || (rm -rf ./mnb-main/venv; exit 1)
fi

if [ -f ./mnb-main/venv/bin/activate ]
then
    source ./mnb-main/venv/bin/activate
elif [ -f  ./mnb-main/venv/Scripts/activate ] # MSYS Windows
then
    source  ./mnb-main/venv/Scripts/activate
elif [ -f ./mnb-main/venv/usr/local/bin/activate ] # macOS
then
    source ./mnb-main/venv/usr/local/bin/activate
else
    echo "Could not find virtualenv activation script"
    exit 1
fi

pip3 install -r ./mnb-main/requirements.txt

if [ -S /var/run/docker.sock ]
then
	docker_host=
else
	docker_host=tcp://localhost:2375
fi

env \
  DOCKER_HOST=$docker_host \
  PYTHONPATH=./mnb-main \
python mnb-main/mnb/climain.py --dev-mode $*


