#!/usr/bin/env bash
#
# Startup script for mnb utility, see https://github.com/berkgaut/mnb-main
#

if [ -S /var/run/docker.sock ]
then
    DOCKER_HOST=
    docker_sock_mount="-v /var/run/docker.sock:/var/run/docker.sock"
else
    DOCKER_HOST=tcp://host.docker.internal:2375
    docker_sock_mount=
fi

docker run \
  --env DOCKER_HOST \
  ${docker_sock_mount} \
  -v "${PWD}:/mnb/run" \
  --rm \
  bberkgaut/mnb:0.7.0 \
  --rootabspath "$(pwd -P)" \
  "$@"
