#!/usr/bin/env bash
# Run tests

set -o errexit
set -o pipefail
set -o nounset

# Determine directory where devmnb is located
MNB_DIR=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)
echo "MNB_DIR=${MNB_DIR}"

SRC_DIR="${MNB_DIR}/src"
TESTS_DIR="${MNB_DIR}/tests"

if which python3 > /dev/null
then
  PYTHON=python3
elif python -c 'import sys; exit(0 if sys.version_info[0]==3 else 1)'
then
  PYTHON=python
else
  echo "Python 3 is required"
  exit 1
fi
echo "PYTHON=${PYTHON}"

VENV_DIR="${MNB_DIR}/venv"
if [ ! -e "${VENV_DIR}" ]
then
  echo "Initialize virtualenv in ${VENV_DIR}"
  mkdir -p "$VENV_DIR"
  ${PYTHON} -m venv "${VENV_DIR}"
fi

if [ -f "${VENV_DIR}/bin/activate" ]
then
    VENV_ACTIVATE="${VENV_DIR}/bin/activate"
elif [ -f  "${VENV_DIR}/Scripts/activate" ] # MSYS Windows
then
    VENV_ACTIVATE="${VENV_DIR}/Scripts/activate"
elif [ -f "${VENV_DIR}/usr/local/bin/activate" ] # macOS
then
    VENV_ACTIVATE="${VENV_DIR}/usr/local/bin/activate"
else
    echo "Could not find virtualenv activation script in directory $VENV_DIR"
    exit 1
fi

echo "Activate virtualenv via ${VENV_ACTIVATE}"
source "${VENV_ACTIVATE}"

echo "Install requirements"
${PYTHON} -m pip install -r "${SRC_DIR}/mnb-core/requirements.txt"

export PYTHONPATH="${SRC_DIR}/mnb-core:${SRC_DIR}/mnb-spec"
echo "PYTHONPATH=${PYTHONPATH}"

export MNB_LIB="${SRC_DIR}/mnb-core/lib"

echo $TESTS_DIR
${PYTHON} -m unittest discover "${TESTS_DIR}" "$@"